[package]
name = "rusty-mastodon"
version = "1.0.0"
authors = [ "Olle Wreede <olle@agical.se>" ]
edition = "2021"

[dependencies]
http = "0.1"
nanoserde = "0.1.32"
vercel_lambda = "*"

[lib]
name = "librustymastodon"
path = "_lib.rs"
